Several updates
appwrite/docker-influxdb pull request #11
Opened 2022-10-01 07:12 UTC by SoftCreatR

- Updated Dockerfile to use Alpine 3.16
- Updated InfluxDB to v1.10 (last v1, consider upgrading to v2!)
- Pinned package versions in Dockerfile
- Dockerfile & init script overhaul

2022-10-05 22:36 UTC, stnguyen90 commented
@SoftCreatR Thanks for the PR! 🤯 Please give us some time to review it.

2022-10-10 20:47 UTC, TorstenDittmann commented
@SoftCreatR you need to bear with me a little bit 😄 these changes are not that easy to review. But this will happend during October - promise 👍🏻

2022-10-10 20:49 UTC, SoftCreatR commented
If you could label this already as hf accepted, the timer can already start 😄

2022-10-17 23:30 UTC, stnguyen90 requested changes
I as able to build and run the branch on GitHub Codespaces:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/1477010/196302319-99496178-0671-4d32-9c51-828054b973c0.png">

2022-10-17 23:30 UTC, stnguyen90 commented on init-influxdb.sh
> +	AUTH_ENABLED="$(grep -iE '^\s*auth-enabled\s*=\s*true' /etc/influxdb/influxdb.conf | grep -io 'true' | cat)"
@SoftCreatR changing the tabs from 2 spaces to an actual tab adds a lot of whitespace changes that makes it harder to review this. Would you please change it back?

2022-10-17 23:35 UTC, SoftCreatR commented on init-influxdb.sh
> +	AUTH_ENABLED="$(grep -iE '^\s*auth-enabled\s*=\s*true' /etc/influxdb/influxdb.conf | grep -io 'true' | cat)"
Done.

2022-10-23 14:39 UTC, TorstenDittmann approved these changes

2022-10-25 22:33 UTC, stnguyen90 approved these changes

2022-12-20 09:45 UTC, merged

2022-12-20 09:45 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)